Controllers/PersonsADOController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using PersonsMVC.Interfaces;
using PersonsMVC.Models;
using PersonsMVC.Tools;

namespace PersonsMVC.Controllers
{
    public class PersonsADOController : Controller
    {
        public IActionResult Index()
        {
            return View();
        } 
        private readonly SqlServer _sqlTools;
        private readonly IDBSettings _settings;
         
        public PersonsADOController (IDBSettings settings)
        {
            _sqlTools = new SqlServer(settings);
            _settings = settings;
        }
        //   GET: Persons/Create
        public IActionResult CreateADO()
        {
            return View();
        }

        // POST: Persons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598. 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateADO([Bind("ID,Name,Age,Email")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                PersonsRepo _repo = new PersonsRepo(_settings);
                await _repo.CreatePersonADO(persons);
            }
            return View(persons);
        }

        // GET: Persons
        public async Task<IActionResult> PersonsADO()
        {
            PersonsRepo _repo = new PersonsRepo(_settings);
            List<Persons> listPersons = await _repo.GetPerson();
            return View(listPersons);
        }

        // GET: Persons/Edit/5
        public async Task<IActionResult> EditADO(int? id)
        {
            PersonsRepo _repo = new PersonsRepo(_settings);
            Persons person = await _repo.EditPerson(id);
            return View(person);
        }

        // SET: Persons
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> EditADO(int id, [Bind("Id,Name,Age,Email")] Persons persons)
        {
            PersonsRepo _repo = new PersonsRepo(_settings);
            await _repo.UpdatePersonsADO(id, persons);
            return View(persons);
        }
        // GET: Persons/Edit/5
        public async Task<IActionResult> SearchForm()
        { 
            return View("SearchForm");
        }
        // GET: Persons/Edit/5
        public async Task<IActionResult> ShowSearchResults(string SearchString)
        {
            PersonsRepo _repo = new PersonsRepo(_settings);
            List<Persons> listPersons = await _repo.SearchPersons(SearchString);
            return View(listPersons);
        }

        [HttpPost]
        public async Task<JsonResult> NameAutocomplete(string prefix)
        {
            PersonsRepo _repo = new PersonsRepo(_settings);
            var List = await _repo.PersonsAutocomplete(prefix);
            return Json(List);
        }

        /// <summary>
        /// Funcion Utilizada para el llenado de un select list,
        /// Nota importante, en el lado del cliente en la funcion AJAX
        /// los elementos declarados en el modelo se leen como camelCase,
        /// de lo contrario no detecta los elementos de la respuesta 
        /// Json
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<JsonResult> GetRoles()
        {
            PersonsRepo _repo = new PersonsRepo(_settings);
            List<PersonsRoles> proles = await _repo.GetPersonsRoles();
            return Json(proles);
        }


        // GET: Persons/Edit/5
        public async Task<IActionResult> ManualTask()
        {
            return View("ManualTask");
        }
        // Action to save table data using ADO.NET
        [HttpPost]
        public async Task<JsonResult> SaveTableData([FromBody] PersonsModel model)
        {
            PersonsRepo _repo = new PersonsRepo(_settings);
            if (model.PersonsTasks != null && model.PersonsTasks.Count > 0)
            {
                await _repo.InsertPersonsManualTsk(model.PersonsTasks);
                return Json(new { success = true, message = "Data saved successfully." });
            }

            return Json(new { success = false, message = "No data to save." });
        }
    }
}

Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PersonsMVC.Data;
using PersonsMVC.Models;

namespace PersonsMVC.Controllers
{
    public class PersonsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Persons
        public async Task<IActionResult> Index()
        {
            return View(await _context.Persons.ToListAsync());
        }

        // GET: Persons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persons = await _context.Persons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (persons == null)
            {
                return NotFound();
            }

            return View(persons);
        }

        // GET: Persons/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Persons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,Email")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                _context.Add(persons);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(persons);
        }

        // GET: Persons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persons = await _context.Persons.FindAsync(id);
            if (persons == null)
            {
                return NotFound();
            }
            return View(persons);
        }

        // POST: Persons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,Email")] Persons persons)
        {
            if (id != persons.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(persons);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonsExists(persons.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persons);
        }

        // GET: Persons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persons = await _context.Persons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (persons == null)
            {
                return NotFound();
            }

            return View(persons);
        }

        // POST: Persons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var persons = await _context.Persons.FindAsync(id);
            if (persons != null)
            {
                _context.Persons.Remove(persons);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonsExists(int id)
        {
            return _context.Persons.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult PersonsTasks(int id)
        {
            Persons? person = new Persons();
            person = _context.Persons.FirstOrDefault(p => p.Id == id);

            //if (person == null)
            //{
            //    return NotFound(); // or redirect somewhere
            //}

            var tasks = _context.RowItems
                .Where(t => t.IDPerson == id)
                .ToList();

            var model = new PersonsModel
            {
                Persons = person,
                PersonsTasks = tasks
            };

            return View("PersonsTasks",model);
        }
        
        [HttpGet]
        public IActionResult PersonsTasksBig(int id)
        {
            Persons? person = new Persons();
            person = _context.Persons.FirstOrDefault(p => p.Id == id);

            //if (person == null)
            //{
            //    return NotFound(); // or redirect somewhere
            //}

            var tasks = _context.RowItems
                .Where(t => t.IDPerson == id)
                .ToList();

            var model = new PersonsModel
            {
                Persons = person,
                PersonsTasks = tasks
            };

            return View("PersonsTasksBig", model);
        }

        [HttpPost]
        public IActionResult SaveModel([FromBody] PersonsModel model)
        {
            if (model.Persons == null) return BadRequest("No person data");

            var existingPerson = _context.Persons.FirstOrDefault(p => p.Id == model.Persons.Id);
            if (existingPerson != null)
            {
                existingPerson.Name = model.Persons.Name;
                existingPerson.Email = model.Persons.Email;
                existingPerson.Age = model.Persons.Age;
            }
            foreach (var task in model.PersonsTasks)
            {
                var existingTask = _context.RowItems.FirstOrDefault(t => t.Idtask == task.Idtask);
                if (existingTask != null)
                {
                    existingTask.Description = task.Description;
                    existingTask.RegisterDate = task.RegisterDate;
                    existingTask.Finished = task.Finished;
                    existingTask.IDPerson = task.IDPerson;
                }
                else
                {
                    _context.RowItems.Add(task);
                }
            }

            _context.SaveChanges();
            return Ok();
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonsMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PersonsMVC.styles.css" asp-append-version="true" />
    <link href="~/css/site.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/jquery-ui-1.14.0/jquery-ui.min.js"></script>
    <link href="~/jquery-ui-1.14.0/jquery-ui.structure.min.css" rel="stylesheet" />
    <link href="~/jquery-ui-1.14.0/jquery-ui.theme.min.css" rel="stylesheet" />

    <script src="~/summernote/bootstrap/js/bootstrap.bundle.min.js"></script>
    <link href="~/summernote/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/summernote/summernote-bs5.min.js"></script>
    <link href="~/summernote/summernote-bs5.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PersonsMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Index">Persons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PersonsADO" asp-action="SearchForm">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PersonsADO" asp-action="ManualTask">ManualTask</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PersonsADO" asp-action="PersonsADO">PersonsADO</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PersonsMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@

    @* <script type="text/javascript" src="Scripts/jquery-3.7.1.min.js"></script> *@


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <base href="~/" />
    <script src="_framework/blazor.server.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>